//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeleYumaEntities1 : DbContext
    {
        public TeleYumaEntities1()
            : base("name=TeleYumaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<OtroGastoes> OtroGastoes { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Productoes> Productoes { get; set; }
        public virtual DbSet<Promo> Promo { get; set; }
        public virtual DbSet<Promocion> Promocion { get; set; }
        public virtual DbSet<RecargaTienda> RecargaTienda { get; set; }
        public virtual DbSet<RecMovilConfig> RecMovilConfig { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<SMS> SMS { get; set; }
        public virtual DbSet<TelintaUsuario> TelintaUsuario { get; set; }
        public virtual DbSet<TipoGastoes> TipoGastoes { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<Credenciales> Credenciales { get; set; }
        public virtual DbSet<DingPromo> DingPromo { get; set; }
        public virtual DbSet<Config> Config { get; set; }
    }
}
