//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DingPromo
    {
        public int Id { get; set; }
        public string ProviderCode { get; set; }
        public string StartUtc { get; set; }
        public string EndUtc { get; set; }
        public string Promo { get; set; }
        public string MontoText { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
    }
}
