//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int IdLogin { get; set; }
        public Nullable<int> i_customer { get; set; }
        public string user { get; set; }
        public Nullable<int> loged { get; set; }
        public int Id { get; set; }
    }
}
