//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecargaTienda
    {
        public int id { get; set; }
        public string IdCuenta { get; set; }
        public string TipoRecarga { get; set; }
        public Nullable<int> CodigoPais { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<double> Impuesto { get; set; }
        public Nullable<double> Importe { get; set; }
        public string Fecha { get; set; }
        public string Estado { get; set; }
    }
}
