//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credenciales
    {
        public int Id { get; set; }
        public string Proveedor { get; set; }
        public string KeyName { get; set; }
        public string KeyValue { get; set; }
        public string KeyGenerate { get; set; }
    }
}
