//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DingPromo
    {
        public int Id { get; set; }
        public string ProviderCode { get; set; }
        public string StartUtc { get; set; }
        public string EndUtc { get; set; }
        public string Promo { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
        public string MontoText { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
