//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion
    {
        public int IdPromocion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Texto { get; set; }
        public string FechaInicio { get; set; }
        public string FechaFin { get; set; }
        public string Noti { get; set; }
        public Nullable<int> IntervaloNoti { get; set; }
        public Nullable<int> Monto { get; set; }
    }
}
