//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int IdReserva { get; set; }
        public Nullable<int> IdPromocion { get; set; }
        public string IdCuenta { get; set; }
        public string Telefono { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<double> TotalPagar { get; set; }
        public string FechaReserva { get; set; }
        public string FechaRecarga { get; set; }
        public string Estado { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> i_account { get; set; }
    }
}
