//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS
    {
        public int Id { get; set; }
        public string i_account { get; set; }
        public string monto { get; set; }
        public string NumeroTelefono { get; set; }
        public string NombreContacto { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Mensaje { get; set; }
        public string RemitenteNumero { get; set; }
        public string RemitenteNombre { get; set; }
        public string Firma { get; set; }
        public Nullable<int> ItemHeight { get; set; }
        public string Destinatario { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> Saliente { get; set; }
        public Nullable<bool> Entrante { get; set; }
        public string Phone1 { get; set; }
        public Nullable<bool> Notify { get; set; }
        public Nullable<int> Idsms { get; set; }
    }
}
