//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleYumaServiceMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class teleyumaEntities1 : DbContext
    {
        public teleyumaEntities1()
            : base("name=teleyumaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Credenciales> Credenciales { get; set; }
        public virtual DbSet<DingPromo> DingPromo { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Promo> Promo { get; set; }
        public virtual DbSet<SMS> SMS { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Promocion> Promocion { get; set; }
        public virtual DbSet<RecargaNauta> RecargaNauta { get; set; }
        public virtual DbSet<RecargaTienda> RecargaTienda { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }      
    }
}
